//
//  LTMANModels.swift
//  LTMANAssignment
//
//  Created by MuMhu on 10/2/2562 BE.
//  Copyright (c) 2562 MuMhu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LTMAN
{
    // MARK: Use cases
    
    enum Celsius
    {
        struct Request
        {
            var fahrenheit: Double
        }
        struct Response
        {
            var celsius: Double
        }
        struct ViewModel
        {
            var celsius: Double
        }
    }
    
    enum Fahrenheit
    {
        struct Request
        {
            var celsius: Double
        }
        struct Response
        {
            var fahrenheit: Double
        }
        struct ViewModel
        {
            var fahrenheit: Double
        }
    }
}
