//
//  LTMANInteractor.swift
//  LTMANAssignment
//
//  Created by MuMhu on 10/2/2562 BE.
//  Copyright (c) 2562 MuMhu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LTMANBusinessLogic
{
    func celToFah(request: LTMAN.Fahrenheit.Request)
    func fahToCel(request: LTMAN.Celsius.Request)
}

protocol LTMANDataStore
{
}

class LTMANInteractor: LTMANBusinessLogic, LTMANDataStore
{
    var presenter: LTMANPresentationLogic?
    
    // MARK: Do something
    
    func celToFah(request: LTMAN.Fahrenheit.Request) {
        let fahrenheit = (((request.celsius / 5) * 9) + 32)
        let response = LTMAN.Fahrenheit.Response(fahrenheit: fahrenheit)
        
        presenter?.presentFahrenheit(response: response)
    }
    
    func fahToCel(request: LTMAN.Celsius.Request) {
        let celsius = (((request.fahrenheit - 32) / 9) * 5)
        let response = LTMAN.Celsius.Response(celsius: celsius)
        
        presenter?.presentCelsius(response: response)
    }
}
